repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.4.0"
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
      - id: check-toml
      - id: check-added-large-files
      - id: debug-statements
  - repo: https://github.com/psf/black
    rev: "23.1.0"
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.1.1"
    hooks:
      - id: mypy
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.0.259'
    hooks:
      - id: ruff
